create table if not exists address
(
    address_id      serial
        constraint address_pk
            primary key,
    street_address1 varchar(50) not null,
    street_address2 varchar(50),
    city            varchar(50) not null,
    region          varchar(50),
    post_code       varchar(10) not null,
    country         varchar(50)
);

create table if not exists business
(
    business_id         serial
        constraint business_pk
            primary key,
    address_id          integer               not null
        constraint business_fk_address
            references address,
    business_name       varchar(50)           not null,
    bank_account_number varchar(50)           not null,
    gst_number          varchar(15),
    email               varchar(50)           not null,
    phone               varchar(10),
    website_link        varchar(255),
    quote_footer        varchar(255),
    invoice_footer      varchar(255),
    deleted             boolean default false not null
);

create table if not exists client
(
    client_id  integer generated by default as identity (start with 1000)
        constraint client_pk
            primary key,
    address_id integer
        constraint client_fk_address
            references address,
    name       varchar(50)           not null,
    email      varchar(50)           not null,
    phone      varchar(10),
    deleted    boolean default false not null
);

create table if not exists product
(
    product_id                bigint default nextval('product_product_id_seq'::regclass) not null
        constraint product_pk
            primary key,
    product_type              boolean,
    user_defined_product_name varchar(50),
    product_description       varchar(255)                                               not null,
    product_price             numeric(10, 2)                                             not null
);

create table if not exists invoice
(
    invoice_id    bigint  default nextval('invoice_invoice_id_seq'::regclass) not null
        constraint invoice_pk
            primary key,
    business_id   integer                                                     not null
        constraint invoice_fk_business
            references business,
    client_id     integer
        constraint invoice_fk_client
            references client,
    creation_date date                                                        not null,
    issued_date   date,
    due_date      date                                                        not null,
    status        varchar(20)                                                 not null,
    total_gst     numeric(10, 2)                                              not null,
    invoice_total numeric(10, 2)                                              not null,
    deleted       boolean default false                                       not null
);

create table if not exists invoice_item
(
    invoice_id bigint                     not null
        constraint invoice_item_fk_invoice
            references invoice,
    product_id bigint                     not null
        constraint invoice_item_fk_product
            references product,
    quantity   integer                    not null,
    discount   numeric(5, 2) default 0.00 not null,
    unit_price numeric(10, 2)             not null,
    subtotal   numeric(10, 2)             not null,
    invoice    bigint,
    constraint invoice_item_pk
        primary key (invoice_id, product_id)
);

create table if not exists quote
(
    quote_id      bigint  default nextval('quote_quote_id_seq'::regclass) not null
        constraint quote_pk
            primary key,
    business_id   integer                                                 not null
        constraint quote_fk_business
            references business,
    client_id     integer
        constraint quote_fk_client
            references client,
    creation_date date                                                    not null,
    issued_date   date,
    expiry_date   date                                                    not null,
    status        varchar(20)                                             not null,
    total_gst     numeric(10, 2)                                          not null,
    quote_total   numeric(10, 2)                                          not null,
    deleted       boolean default false                                   not null
);

create table if not exists quote_item
(
    quote_id   bigint                  not null
        constraint fk_quoteitem_quote
            references quote
            on delete cascade,
    product_id bigint                  not null
        constraint fk_quoteitem_product
            references product,
    quantity   integer                 not null,
    discount   numeric(5, 2) default 0 not null,
    unit_price numeric(10, 2)          not null,
    subtotal   numeric(10, 2)          not null,
    quote      bigint,
    primary key (quote_id, product_id)
);

