/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zero.gui;

/**
 *
 * @author kevin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnClientViewer = new javax.swing.JButton();
        btnTransactionViewer = new javax.swing.JButton();
        btnInvoiceEditor = new javax.swing.JButton();
        btnProductViewer = new javax.swing.JButton();
        btnClientEditor = new javax.swing.JButton();
        btnTransactionEditor = new javax.swing.JButton();
        btnInvoiceViewer = new javax.swing.JButton();
        btnProductEditor = new javax.swing.JButton();
        btnUserInformationEditor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExit.setLabel("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClientViewer.setText("Client");
        btnClientViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientViewerActionPerformed(evt);
            }
        });

        btnTransactionViewer.setText("Transaction");
        btnTransactionViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionViewerActionPerformed(evt);
            }
        });

        btnInvoiceEditor.setText("Invoice");
        btnInvoiceEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceEditorActionPerformed(evt);
            }
        });

        btnProductViewer.setText("Product");
        btnProductViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductViewerActionPerformed(evt);
            }
        });

        btnClientEditor.setText("Client");
        btnClientEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientEditorActionPerformed(evt);
            }
        });

        btnTransactionEditor.setText("Transaction");
        btnTransactionEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionEditorActionPerformed(evt);
            }
        });

        btnInvoiceViewer.setText("Invoice");
        btnInvoiceViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceViewerActionPerformed(evt);
            }
        });

        btnProductEditor.setText("Product");
        btnProductEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductEditorActionPerformed(evt);
            }
        });

        btnUserInformationEditor.setText("User Information");
        btnUserInformationEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserInformationEditorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ZERO tester");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTransactionViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnClientViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnProductViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnInvoiceViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTransactionEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnClientEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnProductEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnUserInformationEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnInvoiceEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUserInformationEditor)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientEditor)
                        .addGap(18, 18, 18)
                        .addComponent(btnProductEditor)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInvoiceEditor)
                            .addComponent(btnInvoiceViewer))
                        .addGap(18, 18, 18)
                        .addComponent(btnTransactionEditor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientViewer)
                        .addGap(18, 18, 18)
                        .addComponent(btnProductViewer)
                        .addGap(59, 59, 59)
                        .addComponent(btnTransactionViewer)))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(415, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClientViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientViewerActionPerformed
        ClientViewer viewer = new ClientViewer(this, true); //add dao
        viewer.setLocationRelativeTo(null);
        viewer.setVisible(true);
    }//GEN-LAST:event_btnClientViewerActionPerformed

    private void btnTransactionViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionViewerActionPerformed
        TransactionViewer viewer = new TransactionViewer(this, true); //add dao
        viewer.setLocationRelativeTo(null);
        viewer.setVisible(true);
    }//GEN-LAST:event_btnTransactionViewerActionPerformed

    private void btnInvoiceEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceEditorActionPerformed
        InvoiceEditor editor = new InvoiceEditor(this, true); //add dao
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
    }//GEN-LAST:event_btnInvoiceEditorActionPerformed

    private void btnProductViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductViewerActionPerformed
        ProductViewer viewer = new ProductViewer(this, true); //add dao
        viewer.setLocationRelativeTo(null);
        viewer.setVisible(true);
    }//GEN-LAST:event_btnProductViewerActionPerformed

    private void btnClientEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientEditorActionPerformed
        ClientEditor editor = new ClientEditor(this, true); //add dao
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
    }//GEN-LAST:event_btnClientEditorActionPerformed

    private void btnTransactionEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionEditorActionPerformed
        UserInformationEditor editor = new UserInformationEditor(this, true); //add dao
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
    }//GEN-LAST:event_btnTransactionEditorActionPerformed

    private void btnInvoiceViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceViewerActionPerformed
        InvoiceViewer viewer = new InvoiceViewer(this, true); //add dao
        viewer.setLocationRelativeTo(null);
        viewer.setVisible(true);
    }//GEN-LAST:event_btnInvoiceViewerActionPerformed

    private void btnProductEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductEditorActionPerformed
        ProductEditor editor = new ProductEditor(this, true); //add dao
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
    }//GEN-LAST:event_btnProductEditorActionPerformed

    private void btnUserInformationEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserInformationEditorActionPerformed
        UserInformationEditor editor = new UserInformationEditor(this, true); //add dao
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
    }//GEN-LAST:event_btnUserInformationEditorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientEditor;
    private javax.swing.JButton btnClientViewer;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInvoiceEditor;
    private javax.swing.JButton btnInvoiceViewer;
    private javax.swing.JButton btnProductEditor;
    private javax.swing.JButton btnProductViewer;
    private javax.swing.JButton btnTransactionEditor;
    private javax.swing.JButton btnTransactionViewer;
    private javax.swing.JButton btnUserInformationEditor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
